## Choosing a Data Set

In [82]:
import pandas as pd

In [83]:
df=pd.read_csv('data/sentiment_analysis/amazon_cells_labelled.txt',names=['sentence', 'label'],sep="\t")
df


sentence  label
0    So there is no way for me to plug it in here i...      0
1                          Good case, Excellent value.      1
2                               Great for the jawbone.      1
3    Tied to charger for conversations lasting more...      0
4                                    The mic is great.      1
..                                                 ...    ...
995  The screen does get smudged easily because it ...      0
996  What a piece of junk.. I lose more calls on th...      0
997                       Item Does Not Match Picture.      0
998  The only thing that disappoint me is the infra...      0
999  You can not answer calls with the unit, never ...      0

[1000 rows x 2 columns]

In [84]:
sentences=df['sentence'].values

 ## taking the data and creating a vocabulary from all the words in all sentences. The collection of texts is also called a corpus in NLP

In [85]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(min_df=0, lowercase=False)

## use the CountVectorizer provided by the scikit-learn library to vectorize sentences. It takes the words of each sentence and creates a vocabulary of all the unique words in the sentences. 

## each sentect will get numerical representation  known as feautre vector 

In [86]:
# vectorizer.fit(sentences)



In [87]:
# vectorizer.vocabulary_

##  When you take the previous  sentences and transform them with the CountVectorizer you will get a vector representing the count of each word of the sentence:
accourding to the vocab

## length of vector of sentecnes if same as length of sentencs in data frame

In [88]:
# vectorizer.transform(sentences).toarray()

In [89]:
# vectorizer.transform(['10 there 10 13 13 for']).toarray()  # word 10 which is at index 0 repeted 2 times in this sentence

## split the data into a training and testing set which will allow you to evaluate the accuracy and see if your model generalizes well.
whether the model is able to perform well on data it has not seen before. This is a way to see if the model is overfitting.

### tart by taking the Yelp data set 
sentences , labels 

In [90]:
labels=df['label'].values
labels

array([0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,

## split the data

In [114]:
from sklearn.model_selection import train_test_split
sentences_train, sentences_test, label_train, label_test = train_test_split(sentences, labels,train_size=0.75, test_size=0.25, random_state=100)

## fit the train sentneces into the vectorizer 
CountVectorizer performs tokenization which separates the sentences into a set of tokens as you saw previously in the vocabulary

In [115]:
vectorizer = CountVectorizer()
vectorizer.fit(sentences_train)

CountVectorizer()

## only vectorize sentences

In [116]:
X_train = vectorizer.transform(sentences_train)
X_test  = vectorizer.transform(sentences_test)
X_train

<750x1551 sparse matrix of type '<class 'numpy.int64'>'
	with 6870 stored elements in Compressed Sparse Row format>

## classification model
 logistic regression 
a form of regression between 0 and 1 based on the input feature vector. By specifying a cutoff value (by default 0.5),

In [117]:
from sklearn.linear_model import LogisticRegression

In [118]:
classifier = LogisticRegression()

In [119]:
classifier.fit(X_train, label_train)

LogisticRegression()

In [120]:
score = classifier.score(X_test, label_test)
print("Accuracy:", score)

Accuracy: 0.82


## testing

In [98]:
vectorizer.transform(['10 there 10 13 13 for']).toarray() 

array([[2, 0, 0, ..., 0, 0, 0]])

In [99]:
vectorizer.transform(['10 there 13 13 for']).toarray() 

array([[1, 0, 0, ..., 0, 0, 0]])